### ISSUE TITLE
use gpt-4

### ISSUE THREAD

**Issue by 0Ut5kWDaVQPfO** [JusticeRage/Gepetto#18]
Can I upgrade from GPT-3.5 to GPT-4, and how should I modify the script? Thank you very much.

**Comment by JusticeRage** [comment]
You can, how this is done is for you to figure out :)
This is something I've planned to do, since the GPT-4 API is available in closed-beta now. But this requires a bit of work because since not all users have access to it, there needs to be a mechanism allowing people to switch between models. So, this is an upcoming feature eventually, but in the meantime you're welcome to look into it and submit a pull request.

**Comment by 0Ut5kWDaVQPfO** [comment]
thank you a lot ,I need study python for a while.then modify it
