### ISSUE TITLE
Web Agent

### ISSUE THREAD

**Issue by xmhwws** [JusticeRage/Gepetto#8]
In some places, the network cannot access Google directly, you need to use a web proxy to access it properly.
Can this excellent plugin support system proxies or designated proxies for web requests?

**Comment by JusticeRage** [comment]
Web requests are handled by [openai-python](https://github.com/openai/openai-python) and that library does not support proxies. This should be possible, since they appear to be using `requests` under the hood, but it will require modifications on their side first. I suggest you open a ticket there and then reopen this one!

A temporary workaround could be to add the following lines at the beginning of the plugin (untested!):

```python
os.environ['HTTP_PROXY'] = os.environ['http_proxy'] = 'http://proxy-domain.tld:3128/'
os.environ['HTTPS_PROXY'] = os.environ['https_proxy'] = 'http://proxy-domain.tld3128/'
```

But I don't think this should be supported directly by Gepetto.
